{% set data = load_setup_py_data() %}

package:
  name: "darts"
  version: "0.6.1"

source:
  # root folder, not the package
  path: "../../../darts"

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps -vv'

requirements:
  host:
    - python
  run:
    - python
    # our template:
    - numpy==1.19.2
    - scipy==1.5.0
    - statsmodels==0.12.2
    - matplotlib==3.2.2
    - pandas==1.1.0
    - ipython==7.15.0
    - tqdm==4.46.1
    - holidays==0.11.1
    - scikit-learn==0.23.2
    - pmdarima==1.8.0
    - pytorch==1.7.1
    - tensorboard==2.4.0
    - pystan==2.19.1.1
    - fbprophet==0.7.1

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: APACHE
  license_file: LICENSE
  summary: {{ data.get('description') }}

extra:
  recipe-maintainers:
    - {{ data.get('maintainer') }}
