{% set data = load_setup_py_data() %}

package:
  name: "darts"
  version: {{ data.get('version') }}

source:
  # root folder, not the package
  path: "../../../darts"

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps -vv'

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - numpy >=1.19.0
    - xarray >=0.18.0
    - scipy >=1.6.0
    - statsmodels >=0.12.0
    - matplotlib-base >=3.4.0
    - pandas >=1.2.0,<1.3.0
    - ipython >=7.22.0
    - tqdm >=4.60.0
    - holidays >=0.11.0
    - scikit-learn >=0.24.0
    - filterpy >=1.4.5
    - joblib >=1.0.0
    - requests >=2.25.0
    - pmdarima >=1.8.0
    - pytorch >=1.8.0,<1.9.0
    - tensorboard >=2.4.0
    - prophet >=1.0.0
    - pystan >=2.19.1.1,<3.0.0.0

test:
  imports:
    - darts
    - darts.dataprocessing
    - darts.dataprocessing.transformers
    - darts.datasets
    - darts.metrics
    - darts.models
    - darts.tests
    - darts.tests.dataprocessing
    - darts.tests.dataprocessing.transformers
    - darts.tests.utils
    - darts.utils
    - darts.utils.data
  source_files:
    - darts
  commands:
    - python -m unittest
  requires:
    - pip
    - testfixtures

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: APACHE
  license_file: LICENSE
  summary: {{ data.get('description') }}

extra:
  recipe-maintainers:
    - unit8co
    - hrzn
    - tomasvanpottelbergh
